Closes #91 length attribute from max data length
atorus-research/xportr pull request #213
Opened 2024-01-10 08:10 UTC by cpiraux

### Thank you for your Pull Request!

We have developed a Pull Request template to aid you and our reviewers. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the xportr codebase remains robust and consistent.

### The scope of `{xportr}`

`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs. We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request meets this **scope of {xportr}**. If your Pull Request moves beyond this scope, please get in touch with the `{xportr}` team on [slack](https://pharmaverse.slack.com/archives/C030EB2M4GM) or create an issue to discuss.

Please check off each task box as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

### Changes Description

- Add a function argument to get the length either from metadata or data.
- Add a utility function to get the maximum data length per variable, facilitating the automation of metadata length updates.

### Task List

- [x] The spirit of xportr is met in your Pull Request
- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Summary of changes filled out in the above Changes Description. Can be removed or left blank if changes are minor/self-explanatory.
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Use `styler` package and functions to style files accordingly.
- [x] Updated relevant unit tests or have written new unit tests. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Unit-Tests) for conventions used in this package.
- [x] Creation/updated relevant roxygen headers and examples. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers) for conventions used in this package.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new/updated functions occur on the "Reference" page.
- [x] Update NEWS.md if the changes pertain to a user-facing function (i.e. it has an @export tag) or documentation aimed at users (rather than developers)
- [x] Make sure that the pacakge version in the NEWS.md and DESCRIPTION file is same. Don't worry about updating the version because it will be auto-updated using the `vbump.yaml` CI.
- [x] Address any updates needed for vignettes and/or templates
- [x] Link the issue Development Panel so that it closes after successful merging.
- [x] Fix merge conflicts
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-01-16 16:44 UTC, bms63 commented
Hi @cpiraux going to have to resolve merge conflicts - a big PR was just merged.  Let me know if you need help

2024-01-25 16:29 UTC, averissimo reviewed
Some comments on parameter assertion

2024-01-25 16:29 UTC, averissimo commented on R/length.R
>    if (!missing(metacore)) {
Suggestion to use `match.args` just like other R functions (check `?stats::cor`)

The first element becomes the default value

```suggestion
                          length = "metadata",
                          verbose = getOption("xportr.length_verbose", "none"),
                          metacore = deprecated()) {
  length <- match.args(length)
  if (!missing(metacore)) {
```

Documentation will look like this:

![image](https://github.com/atorus-research/xportr/assets/211358/b091ad79-cc62-4876-951f-4a589fdc9048)

2024-01-25 16:29 UTC, averissimo commented on R/messages.R
> +  if (nrow(max_length) > 0) {
Add assertion on parameters

```suggestion
  assert_data_frame(max_length)
  assert_choice(verbose, choices = .internal_verbose_choices)
  
  if (nrow(max_length) > 0) {
```

2024-01-28 22:51 UTC, bms63 commented
@cpiraux I was missing around with this PR.  I noticed that one line had `match.args` and not `match.arg` which was causing the R-CMD checks to fail.

Now this new one is showing up.  I ran out of time to investigate.  Hoping you see the underlying issue!! 

![image](https://github.com/atorus-research/xportr/assets/10111024/cb3b2a4a-42cf-4b08-a2c6-a8a8bf2ed423)

2024-01-29 19:27 UTC, bms63 commented
@averissimo could you take a look at how we are using `match.arg` I am not able to get it to work.

@cpiraux I had to put in your argument into the vignettes and update the example for `xportr_length()` and things are working again!!  yay!

Some thoughts:

1) Does `xportr_lenght(lenght = "metadata")` need to be integrated into `xportr_metadata` and `xportr_write_all()` functions? @EeethB  something for us to ponder (lets address in separate issue/PR if we think it needs to be updated.)

2) @cpiraux probably shoudl build an example in the documents (function and vignettes) that allows the user to specify `length = "data"` and show user how it works

3) I think the `length` argument should be re-visited as I found it a bit confusing.  Maybe `variable_source_length` or `source_length`, `length_source`?

Okay!!  this one is almost to the finish line.  Way to go!!

2024-01-30 18:55 UTC, averissimo commented
:facepalm: I had a typo on the suggestion, sorry about the `match.args` -> `match.args`

@bms63 Traced the issue to the "new" order of parameters. vignettes, have variations of the snippet below where they assume that the 3rd element is the `verbose` instead of `metadata`.

```R
adsl %>%
  xportr_type(var_spec, "ADSL", "message") %>%
  xportr_length(var_spec, "ADSL", "message")
#...
```

2024-01-30 19:00 UTC, averissimo commented on R/length.R
> +                          length = c("metadata", "data"),
Should we add this parameter after `verbose`?

I understand and support the reason for the current order, however, an error was triggered on our vignettes due to parameter order and I'm a bit concerned about our users facing the same problem

```r
# example
xportr_length(adsl, metadata, "adsl", "message")
#> Error in match.arg(length) : 'arg' should be one of “metadata”, “data”
```

Thoughts?

2024-02-08 15:10 UTC, bms63 commented on NEWS.md
> +*New argument in `xportr_length()` allows selection between the length from metadata, as previously done, or from the calculated maximum length per variable when `length_source` is set to “data” (#91
```suggestion
* New argument in `xportr_length()` allows selection between the length from metadata, as previously done, or from the calculated maximum length per variable when `length_source` is set to “data” (#91)
```

2024-02-08 15:12 UTC, bms63 commented on R/length.R
> +#' adsl <- xportr_length(adsl, metadata, domain = "adsl", length = "metadata")
```suggestion
#' adsl <- xportr_length(adsl, metadata, domain = "adsl", length_source = "metadata")
```

2024-02-08 15:14 UTC, bms63 commented on tests/testthat/test-length.R
All these will need to have the argument updated to `length_source`

2024-02-08 15:14 UTC, bms63 commented on vignettes/deepdive.Rmd
> +  xportr_length(length = "metadata") %>%
wondering if this can be removed since metadata is default??

2024-02-08 15:15 UTC, bms63 requested changes
Very close!!  Just need to update where ever length is used to length_source

2024-02-11 16:29 UTC, bms63 approved these changes
@cpiraux You are amazing!!  Thanks for seeing this one through for us.

2024-02-11 16:30 UTC, merged