Closes #136 removing used SASlength from functions
atorus-research/xportr pull request #216
Opened 2024-01-11 16:46 UTC by sadchla-codes

### Thank you for your Pull Request!

We have developed a Pull Request template to aid you and our reviewers. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the xportr codebase remains robust and consistent.

### The scope of `{xportr}`

`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs. We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request meets this **scope of {xportr}**. If your Pull Request moves beyond this scope, please get in touch with the `{xportr}` team on [slack](https://pharmaverse.slack.com/archives/C030EB2M4GM) or create an issue to discuss.

Please check off each task box as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

### Changes Description

_(descriptions of changes)_

### Task List

- [ ] The spirit of xportr is met in your Pull Request
- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Summary of changes filled out in the above Changes Description. Can be removed or left blank if changes are minor/self-explanatory.
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Use `styler` package and functions to style files accordingly.
- [ ] Updated relevant unit tests or have written new unit tests. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Unit-Tests) for conventions used in this package.
- [ ] Creation/updated relevant roxygen headers and examples. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers) for conventions used in this package.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new/updated functions occur on the "Reference" page.
- [ ] Update NEWS.md if the changes pertain to a user-facing function (i.e. it has an @export tag) or documentation aimed at users (rather than developers)
- [ ] Make sure that the pacakge version in the NEWS.md and DESCRIPTION file is same. Don't worry about updating the version because it will be auto-updated using the `vbump.yaml` CI.
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Link the issue Development Panel so that it closes after successful merging.
- [ ] Fix merge conflicts
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-01-18 10:56 UTC, cpiraux requested changes
Thank you for implementing this. I've included a few comments for your review.

2024-01-18 10:56 UTC, cpiraux commented on R/length.R
> +#' @return Data frame with SAS default length attributes for each variable.
```suggestion
#' @return Data frame with 'width' attributes that store the SAS length for each variable.
```

2024-01-18 10:56 UTC, cpiraux commented on R/utils-xportr.R
> +  types <- tolower(extract_attr(data, attr = "type"))
The `xport_type()` function does not add any attributes, so I suggest to remove the type check.

2024-01-18 10:56 UTC, cpiraux commented on R/write.R
>  #'
We can keep the lines for the SAS length and replace 'SASlength' by 'width' :
#' * SAS length are stored in the "width" attribute.

2024-01-18 10:56 UTC, cpiraux commented on tests/testthat/test-utils-xportr.R
> +  attr(df$B, "type") <- "list"
Test to be removed if `xpt_validate()` is updated to remove type check

2024-01-18 10:56 UTC, cpiraux commented on R/write.R
>  #'   * SAS format are stored in the "SASformat" attribute.
The name for the SAS format attribute is 'format.sas'. Maybe we should also update 'SASformat' to  'format.sas', what do you think?

2024-01-18 10:56 UTC, cpiraux commented on R/utils-xportr.R
> +extract_attr <- function(data, attr = c("label", "format.sas", "type")) {
There is no "type" attribute added by the function `xport_type()`

2024-01-20 00:24 UTC, EeethB reviewed
No further comments besides Celine's, thanks both for the work on this!

2024-01-30 16:43 UTC, elimillera commented
@sadchla-codes Are you able to take care of the rest of those comments?

2024-02-01 13:55 UTC, sadchla-codes commented
> @sadchla-codes Are you able to take care of the rest of those comments?

Yes

2024-02-05 15:05 UTC, cpiraux approved these changes
Looks good to me!

2024-02-05 15:52 UTC, merged