Closes #207 xportr_length for missing length in metadata
atorus-research/xportr pull request #238
Opened 2024-02-15 12:26 UTC by cpiraux

### Thank you for your Pull Request!

We have developed a Pull Request template to aid you and our reviewers. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the xportr codebase remains robust and consistent.

### The scope of `{xportr}`

`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs. We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request meets this **scope of {xportr}**. If your Pull Request moves beyond this scope, please get in touch with the `{xportr}` team on [slack](https://pharmaverse.slack.com/archives/C030EB2M4GM) or create an issue to discuss.

Please check off each task box as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

### Changes Description

Assigns the maximum length value instead of 200 for a character variable when the length is missing in the metadata

### Task List

- [ ] The spirit of xportr is met in your Pull Request
- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Summary of changes filled out in the above Changes Description. Can be removed or left blank if changes are minor/self-explanatory.
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Use `styler` package and functions to style files accordingly.
- [ ] New functions or arguments follow established convention found in the [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers).
- [ ] Updated relevant unit tests or have written new unit tests. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Unit-Tests) for conventions used in this package.
- [ ] Creation/updated relevant roxygen headers and examples. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers) for conventions used in this package.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new/updated functions occur on the "Reference" page.
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] The `NEWS.md` entry should go under the `# xportr development version` section. Don't worry about updating the version because it will be auto-updated using the `vbump.yaml` CI.
- [ ] Address any updates needed for vignettes and/or templates.
- [ ] Link the issue Development Panel so that it closes after successful merging.
- [ ] The developer is responsible for fixing merge conflicts not the Reviewer.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-02-16 15:24 UTC, bms63 commented on tests/testthat/test-metadata.R
> +  # Max length is the imputed length for character and 8 for other data types as in impute_length()
impute_length() was removed.  Can this test subject header be updated as well.

2024-02-16 15:25 UTC, bms63 requested changes
Just a small update to test and please fix lintr issue.  Thanks again for this work @cpiraux !!!!!!!!!!!!!!!!!!!!!!!!!!!!!

2024-02-20 12:49 UTC, cpiraux commented
What should I do to resolve this lint error?
![image](https://github.com/atorus-research/xportr/assets/69685640/bf58fa6a-2169-485c-9f7d-add2aa7973b2)

2024-02-20 14:14 UTC, bms63 commented
> What should I do to resolve this lint error? ![image](https://private-user-images.githubusercontent.com/69685640/306266920-bf58fa6a-2169-485c-9f7d-add2aa7973b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0Mzg2OTksIm5iZiI6MTcwODQzODM5OSwicGF0aCI6Ii82OTY4NTY0MC8zMDYyNjY5MjAtYmY1OGZhNmEtMjE2OS00ODVjLTlmN2QtYWRkMmFhNzk3M2IyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDE0MTMxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRkNmY3ZDM2NmE0NGMxZjg1ZGJhMTliZmY4M2U0MjBiODZlOTg4NTkxMGRhODhlNmYyODM5YTBiMjFkZmJlMTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mPZk0vx15_-5fkhS1_5QJ6Yn9l2vFa8HuURbcLXJRDo)

It has to do with the number of conditions being used in a function.  https://en.wikipedia.org/wiki/Cyclomatic_complexity

I increased it to 18 in the `.lintr` file so this would check.  Will make an issue for someone to look into for next release.

2024-02-20 14:50 UTC, bms63 approved these changes

2024-02-20 18:16 UTC, merged