Closes #223 Test code clean up
atorus-research/xportr pull request #248
Opened 2024-02-22 05:40 UTC by sadchla-codes

### Thank you for your Pull Request!

We have developed a Pull Request template to aid you and our reviewers. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the xportr codebase remains robust and consistent.

### The scope of `{xportr}`

`{xportr}`'s scope is to enable R users to write out submission compliant `xpt` files that can be delivered to a Health Authority or to downstream validation software programs. We see labels, lengths, types, ordering and formats from a dataset specification object (SDTM and ADaM) as being our primary focus. We also see messaging and warnings to users around applying information from the specification file as a primary focus. Please make sure your Pull Request meets this **scope of {xportr}**. If your Pull Request moves beyond this scope, please get in touch with the `{xportr}` team on [slack](https://pharmaverse.slack.com/archives/C030EB2M4GM) or create an issue to discuss.

Please check off each task box as an acknowledgment that you completed the task. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

### Changes Description

_(descriptions of changes)_

### Task List

- [ ] The spirit of xportr is met in your Pull Request
- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Summary of changes filled out in the above Changes Description. Can be removed or left blank if changes are minor/self-explanatory.
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Use `styler` package and functions to style files accordingly.
- [ ] New functions or arguments follow established convention found in the [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers).
- [ ] Updated relevant unit tests or have written new unit tests. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Unit-Tests) for conventions used in this package.
- [ ] Creation/updated relevant roxygen headers and examples. See our [Wiki](https://github.com/atorus-research/xportr/wiki/Style-Guide-for-Roxygen-Headers) for conventions used in this package.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Run `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new/updated functions occur on the "Reference" page.
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] The `NEWS.md` entry should go under the `# xportr development version` section. Don't worry about updating the version because it will be auto-updated using the `vbump.yaml` CI.
- [ ] Address any updates needed for vignettes and/or templates.
- [ ] Link the issue Development Panel so that it closes after successful merging.
- [ ] The developer is responsible for fixing merge conflicts not the Reviewer.
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

2024-03-01 16:45 UTC, averissimo commented on tests/testthat/test-metadata.R
> +  if (requireNamespace("magrittr", quietly = TRUE)) {
`{magrittr}` is on `Imports` in the `DESCRIPTION` file.

We can safely assume it is installed and remove all of these `requreNamespace("magrittr", ...)`

2024-03-07 01:37 UTC, bms63 reviewed
Did you use the admiraldev add-in for this?  If not, maybe we should look into making that a standalone tool

2024-03-07 01:41 UTC, bms63 commented on tests/testthat/test-metadata.R
Do we still need the haven and readxl packages in these tests?

2024-03-07 01:41 UTC, bms63 commented on tests/testthat/test-metadata.R
Can they be removed so the lintr becomes happy again?

2024-03-07 01:43 UTC, bms63 reviewed
Can we just suspend the lintr check for indentation and just have the styler one?

Also can these lines be returned onto the next line where appropriate?

![image](https://github.com/atorus-research/xportr/assets/10111024/e7b31c39-b497-49a5-bf13-f0b00fb7a3d2)

2024-03-08 15:23 UTC, sadchla-codes commented
> Did you use the admiraldev add-in for this? If not, maybe we should look into making that a standalone tool

I did use admiraldev add-in

2024-03-10 19:53 UTC, bms63 commented on DESCRIPTION
> +    readxl
where are we using this?  how come it got moved from Suggest to Imports?

2024-03-10 19:54 UTC, bms63 requested changes
im weary to move readxl to Imports? why are we doing this?

2024-03-14 14:20 UTC, sadchla-codes commented
> im weary to move readxl to Imports? why are we doing this?

Hi @bms63 it was given me a dependency error in the R CMD check, but i made some slight updates. It seems to be working great now and readxl is back to suggest

2024-03-14 14:42 UTC, bms63 commented
Thanks for organizing and cleaning up our test code.  Much nicer!!!

2024-03-14 14:42 UTC, merged