Add logic to convert any null or NA formats to "" for haven.
atorus-research/xportr pull request #74
Opened 2023-02-20 20:07 UTC by elimillera

This closes #69.

Idea here is to remove any null or NA formats and convert them to "". This is due to a limitation in haven that will break any NA 'sas.formats'

2023-02-20 20:09 UTC, bms63 requested changes
Awesome! Thanks Eli!  Can we put some stuff into the changelog for this and other issues.  I feel like this is more of a minor release as we are really just fixing bugs and lingering issues we left from last year.

2023-02-21 21:40 UTC, elimillera commented
@bms63 Should be good!

2023-02-22 17:59 UTC, bms63 commented on tests/testthat/test-metadata.R
>  })
Could we break this into two tests?  One where we just look at the easy case where all the variables (x,y) have formats applied

and then a 2nd Case where we have x,y,z,abc and test that function works when there is an NA.

and update the test_that("SAS format..." for both cases.

2023-02-23 16:28 UTC, bms63 approved these changes
Love it!!  Thanks Eli

2023-02-23 16:29 UTC, merged