Improvements for 'xportr_type'
atorus-research/xportr pull request #80
Opened 2023-03-10 05:56 UTC by elimillera

Still doing some doc updates. I'll add more context in a couple days

2023-04-25 19:24 UTC, bms63 commented
@elimillera I merged in `devel` and this is falling over now.  :(

2023-05-05 13:20 UTC, elimillera commented
Closes #77 #65

2023-05-05 21:07 UTC, bms63 commented on R/type.R
> +      # wants 'character' coersed to character
```suggestion
      # _character is used here as a mask of character, in case someone doesn't
      # want 'character' coerced to character
```

2023-05-05 21:08 UTC, bms63 commented on tests/testthat/test-type.R
> +test_that("NAs are handled as expected", {
```suggestion
test_that("xportr_type: NAs are handled as expected", {
```

2023-05-05 21:10 UTC, bms63 requested changes
Is this a related to issue #65?  was totally sure - can we also get a blurb in the News.md on this update/fix

2023-05-09 17:38 UTC, bms63 approved these changes
This looks good to me - just some styling issues to address.

2023-05-11 12:41 UTC, cpiraux commented
Zzz.R List of character type and numeric type 

Define-XML data type can be text, integer, float, datetime, date, time,  partialdate, partialtime, partialdatetime,   incompletedatetime, durationdatetime, intervaldatetime

These types should be added in xportr.character_types or xportr.numeric_types

“num” could also be added in numeric type such as char in character type. Num and Char are sometimes present in specs as it comes from the SAS proc content of dataset.

xportr.character_types = c("character", "char", "text", "date", "posixct", "posixt", "datetime", "time", "partialdate", "partialtime", "partialdatetime", "incompletedatetime", "durationdatetime", "intervaldatetime")

xportr.numeric_types = c("integer", "numeric", "num", "float", )

2023-05-12 17:10 UTC, merged